Fix ps_mysqld_helper.sh script errors
Fix script error with uninitialised STATUS_THP_SYSTEM which causes:

/usr/bin/ps_mysqld_helper: line 13: [: =: unary operator expected

Fix script error with incorrectly initialised JEMALLOC_LOCATION writing LD_PRELOAD=0 to config which causes:

ERROR: ld.so: object '0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.